@HotelListing.Api_HostAddress = https://localhost:7000

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name":"Json Hotel",
  "address": "yes sir st",
  "rating": 3.7,
  "countryId": 5
}

###

GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  
    "name": "Panama",
    "shortName": "PN"
}

###

@id=5
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
@id=8
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###
@id=3
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id" : 3 ,
  "Name":"Jesus Palace",
  "address": "the lord ave",
  "rating": 5,
  "countryId": 4
}

###
@id=3
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/countries

###
