@HotelListing.Api_HostAddress = https://localhost:7000

GET {{HotelListing.Api_HostAddress}}/api/countries

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

@id=5
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
@id=5
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 5,
  "Name" : "Israeli Hotel",
  "Address" : "Bassora, Iraq",
  "Rating" : 3.5,
  "CountryId": 4
}

###
@id=3
PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "Id": 3,
  "Name": "United States of America",
  "ShortName": "USA"
}

###
